// Generated by Wrangler by running `wrangler types`

interface Env {
	PARTSIZE: 10485760;
	UPLOAD_WORKER_URL: string;
	debug: string;
	S3_ENDPOINT: string;
	S3_REGION: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	do: DurableObjectNamespace<import("./src/index").multiPartList>;
	queue: Queue;
}
