#:schema node_modules/wrangler/config-schema.json
name = "multi-part-coordinator"
main = "src/index.ts"
compatibility_date = "2024-10-01"
workers_dev = false
route= { custom_domain = true, pattern = "my.domain.example.com"} # change to your domain

[vars]
PARTSIZE = 10485760 # 10 * 1024 * 1024 = 10MB default
debug= false # verbose logging
UPLOAD_WORKER_URL="http://my.example.url.com" # multi-part-upload worker URL
S3_ENDPOINT="my S3 endpoint"
S3_REGION="my S3 region"
AWS_ACCESS_KEY_ID='my S3 ID' # secret
AWS_SECRET_ACCESS_KEY= 'my S3 KEY' # secret

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects
[[durable_objects.bindings]]
name = "do"
class_name = "multiPartList"

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["multiPartList"]

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#queues
[[queues.producers]]
binding = "queue"
queue = "multi-part-upload" # change to your queue

# Bind a Queue consumer. Queue Consumers can retrieve tasks scheduled by Producers to act on them.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#queues
[[queues.consumers]]
queue = "multi-part-upload"  # change to your queue